dojo/cred/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.apps import apps
import views

urlpatterns = [
    url(r'^cred/add', views.new_cred, name='add_cred'),
    url(r'^cred/(?P<ttid>\d+)/view$', views.view_cred_details, name='view_cred_details'),
    url(r'^cred/(?P<ttid>\d+)/edit$', views.edit_cred, name='edit_cred'),
    url(r'^cred/(?P<ttid>\d+)/delete$', views.delete_cred, name='delete_cred'),
    url(r'^cred/(?P<ttid>\d+)/selenium$', views.view_selenium, name='view_selenium'),
    url(r'^cred$', views.cred, name='cred'),
    url(r'^product/(?P<pid>\d+)/cred/add$', views.new_cred_product, name='new_cred_product'),
    url(r'^product/(?P<pid>\d+)/cred/(?P<ttid>\d+)/edit$', views.edit_cred_product, name='edit_cred_product'),
    url(r'^product/(?P<pid>\d+)/cred/(?P<ttid>\d+)/view$', views.view_cred_product, name='view_cred_product'),
    url(r'^product/(?P<pid>\d+)/cred/(?P<ttid>\d+)/delete$', views.delete_cred_product, name='delete_cred_product'),
    url(r'^engagement/(?P<eid>\d+)/cred/add$', views.new_cred_product_engagement, name='new_cred_product_engagement'),
    url(r'^engagement/(?P<eid>\d+)/cred/(?P<ttid>\d+)/view$', views.view_cred_product_engagement,
        name='view_cred_product_engagement'),
    url(r'^engagement/(?P<eid>\d+)/cred/(?P<ttid>\d+)/delete$', views.delete_cred_engagement,
        name='delete_cred_engagement'),
    url(r'^test/(?P<tid>\d+)/cred/add$', views.new_cred_engagement_test, name='new_cred_engagement_test'),
    url(r'^test/(?P<tid>\d+)/cred/(?P<ttid>\d+)/view$', views.view_cred_engagement_test,
        name='view_cred_engagement_test'),
    url(r'^test/(?P<tid>\d+)/cred/(?P<ttid>\d+)/delete$', views.delete_cred_test, name='delete_cred_test'),
    url(r'^finding/(?P<fid>\d+)/cred/add$', views.new_cred_finding, name='new_cred_finding'),
    url(r'^finding/(?P<fid>\d+)/cred/(?P<ttid>\d+)/view$', views.view_cred_finding, name='view_cred_finding'),
    url(r'^finding/(?P<fid>\d+)/cred/(?P<ttid>\d+)/delete$', views.delete_cred_finding, name='delete_cred_finding'), ]

dojo/home/urls.py
from django.conf.urls import url

from dojo.home import views

urlpatterns = [
    #  dojo home pages
    url(r'^$', views.home, name='home'),
    url(r'^dashboard$', views.dashboard, name='dashboard'),
]

dojo/scan/urls.py
from django.conf.urls import url

from dojo.scan import views

urlpatterns = [
    # scans and scan settings
    url(r'^scan/(?P<sid>\d+)$', views.view_scan,
        name='view_scan'),
    url(r'^product/(?P<pid>\d+)/scan/add$', views.gmap, name='gmap'),
    url(r'^product/(?P<pid>\d+)/scan/(?P<sid>\d+)/settings$',
        views.view_scan_settings, name='view_scan_settings'),
    url(r'^product/(?P<pid>\d+)/scan/(?P<sid>\d+)/edit$',
        views.edit_scan_settings, name='edit_scan_settings'),
    # other
    url(r'^launch_va/(?P<pid>\d+)$', views.launch_va,
        name='launch_va'),
]

dojo/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from tastypie.api import Api

from dojo import views
from dojo.api import UserResource, ProductResource, EngagementResource, \
    TestResource, FindingResource, ScanSettingsResource, ScanResource, \
    StubFindingResource, FindingTemplateResource, ImportScanResource, \
    ReImportScanResource, JiraResource, JIRA_ConfResource, EndpointResource, \
    JIRA_IssueResource, ToolProductSettingsResource, Tool_ConfigurationResource, \
    Tool_TypeResource, LanguagesResource, LanguageTypeResource, App_AnalysisResource, \
    BuildDetails
from dojo.utils import get_system_setting
from dojo.development_environment.urls import urlpatterns as dev_env_urls
from dojo.endpoint.urls import urlpatterns as endpoint_urls
from dojo.engagement.urls import urlpatterns as eng_urls
from dojo.finding.urls import urlpatterns as finding_urls
from dojo.home.urls import urlpatterns as home_urls
from dojo.metrics.urls import urlpatterns as metrics_urls
from dojo.product.urls import urlpatterns as prod_urls
from dojo.product_type.urls import urlpatterns as pt_urls
from dojo.reports.urls import urlpatterns as reports_urls
from dojo.scan.urls import urlpatterns as scan_urls
from dojo.search.urls import urlpatterns as search_urls
from dojo.test.urls import urlpatterns as test_urls
from dojo.test_type.urls import urlpatterns as test_type_urls
from dojo.user.urls import urlpatterns as user_urls
from dojo.jira_link.urls import urlpatterns as jira_urls
from dojo.tool_type.urls import urlpatterns as tool_type_urls
from dojo.tool_config.urls import urlpatterns as tool_config_urls
from dojo.tool_product.urls import urlpatterns as tool_product_urls
from dojo.cred.urls import urlpatterns as cred_urls
from dojo.system_settings.urls import urlpatterns as system_settings_urls
from dojo.notifications.urls import urlpatterns as notifications_urls
from dojo.object.urls import urlpatterns as object_urls
from dojo.benchmark.urls import urlpatterns as benchmark_urls
import sys

admin.autodiscover()

"""
        Bind multiple resources together to form a coherent API.
"""
v1_api = Api(api_name='v1', )
v1_api.register(UserResource())
v1_api.register(ProductResource())
v1_api.register(EngagementResource())
v1_api.register(TestResource())
v1_api.register(FindingResource())
v1_api.register(FindingTemplateResource())
v1_api.register(ScanSettingsResource())
v1_api.register(ScanResource())
v1_api.register(StubFindingResource())
v1_api.register(ImportScanResource())
v1_api.register(ReImportScanResource())
v1_api.register(EndpointResource())
v1_api.register(JiraResource())
v1_api.register(JIRA_ConfResource())
v1_api.register(JIRA_IssueResource())
v1_api.register(ToolProductSettingsResource())
v1_api.register(Tool_ConfigurationResource())
v1_api.register(Tool_TypeResource())
v1_api.register(LanguagesResource())
v1_api.register(LanguageTypeResource())
v1_api.register(App_AnalysisResource())
v1_api.register(BuildDetails())
# v1_api.register(IPScanResource())


ur = []
ur += dev_env_urls
ur += endpoint_urls
ur += eng_urls
ur += finding_urls
ur += home_urls
ur += metrics_urls
ur += prod_urls
ur += pt_urls
ur += reports_urls
ur += scan_urls
ur += search_urls
ur += test_type_urls
ur += test_urls
ur += user_urls
ur += jira_urls
ur += tool_type_urls
ur += tool_config_urls
ur += tool_product_urls
ur += cred_urls
ur += system_settings_urls
ur += notifications_urls
ur += object_urls
ur += benchmark_urls

from tastypie_swagger.views import SwaggerView, ResourcesView, SchemaView

swagger_urls = [
    url(r'^$', SwaggerView.as_view(), name='index'),
    url(r'^resources/$', ResourcesView.as_view(), name='resources'),
    url(r'^schema/(?P<resource>\S+)$', SchemaView.as_view()),
    url(r'^schema/$', SchemaView.as_view(), name='schema'),
]



urlpatterns = [
    #  django admin
    url(r'^%sadmin/' % get_system_setting('url_prefix'), include(admin.site.urls)),
    #  tastypie api
    url(r'^%sapi/' % get_system_setting('url_prefix'), include(v1_api.urls)),
    # api doc urls
    url(r'%sapi/v1/doc/' % get_system_setting('url_prefix'),
        include(swagger_urls, namespace='tastypie_swagger'),
        kwargs={
            "tastypie_api_module": "dojo.urls.v1_api",
            "namespace": "tastypie_swagger",
            "version": "1.0"}),
    # action history
    url(r'^%shistory/(?P<cid>\d+)/(?P<oid>\d+)$' % get_system_setting('url_prefix'), views.action_history,
        name='action_history'),
    url(r'^%s' % get_system_setting('url_prefix'), include(ur)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dojo/models.py
import base64
import logging
import os
import re
from datetime import datetime
from uuid import uuid4

from django.conf import settings

from watson import search as watson
from auditlog.registry import auditlog
from django.contrib import admin
from django.contrib.auth import get_user_model
from django.core.urlresolvers import reverse
from django.core.validators import RegexValidator
from django.db import models
from django.db.models import Q
from django.utils.timezone import now
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToCover
from django.utils import timezone
from pytz import all_timezones
from tagging.registry import register as tag_register
from multiselectfield import MultiSelectField
import hashlib
from django import forms

fmt = getattr(settings, 'LOG_FORMAT', None)
lvl = getattr(settings, 'LOG_LEVEL', logging.DEBUG)

logging.basicConfig(format=fmt, level=lvl)


class System_Settings(models.Model):
    enable_deduplication = models.BooleanField(
        default=False,
        blank=False,
        verbose_name='Deduplicate findings',
        help_text="With this setting turned on, Dojo deduplicates findings by "
                  "comparing endpoints, cwe fields, and titles. "
                  "If two findings share a URL and have the same CWE or "
                  "title, Dojo marks the less recent finding as a duplicate. "
                  "When deduplication is enabled, a list of "
                  "deduplicated findings is added to the engagement view.")
    delete_dupulicates = models.BooleanField(default=False, blank=False)
    max_dupes = models.IntegerField(blank=True, null=True,
                                    verbose_name='Max Duplicates',
                                    help_text="When enabled, if a single "
                                              "issue reaches the maximum "
                                              "number of duplicates, the "
                                              "oldest will be deleted.")
    enable_jira = models.BooleanField(default=False,
                                      verbose_name='Enable JIRA integration',
                                      blank=False)
    jira_choices = (('Critical', 'Critical'),
                    ('High', 'High'),
                    ('Medium', 'Medium'),
                    ('Low', 'Low'))
    jira_minimum_severity = models.CharField(max_length=20, blank=True,
                                             null=True, choices=jira_choices,
                                             default='None')
    jira_labels = models.CharField(max_length=200, blank=True, null=True,
                                   help_text='JIRA issue labels space seperated')
    enable_slack_notifications = \
        models.BooleanField(default=False,
                            verbose_name='Enable Slack notifications',
                            blank=False)
    slack_channel = models.CharField(max_length=100, default='', blank=True)
    slack_token = models.CharField(max_length=100, default='', blank=True,
                                   help_text='Token required for interacting '
                                             'with Slack. Get one at '
                                             'https://api.slack.com/tokens')
    slack_username = models.CharField(max_length=100, default='', blank=True)
    enable_hipchat_notifications = \
        models.BooleanField(default=False,
                            verbose_name='Enable HipChat notifications',
                            blank=False)
    hipchat_site = models.CharField(max_length=100, default='', blank=True,
                                    help_text='The full fqdn of your '
                                              'hipchat site, e.g. '
                                              '"yoursite.hipchat.com"')
    hipchat_channel = models.CharField(max_length=100, default='', blank=True)
    hipchat_token = \
        models.CharField(max_length=100, default='', blank=True,
                         help_text='Token required for interacting with '
                                   'HipChat. Get one at '
                                   'https://patriktest.hipchat.com/addons/')
    enable_mail_notifications = models.BooleanField(default=False, blank=False)
    mail_notifications_from = models.CharField(max_length=200,
                                               default='from@example.com',
                                               blank=True)
    mail_notifications_to = models.CharField(max_length=200, default='',
                                             blank=True)
    s_finding_severity_naming = \
        models.BooleanField(default=False, blank=False,
                            help_text='With this setting turned on, Dojo '
                                      'will display S0, S1, S2, etc in most '
                                      'places, whereas if turned off '
                                      'Critical, High, Medium, etc will '
                                      'be displayed.')
    false_positive_history = models.BooleanField(default=False)

    url_prefix = models.CharField(max_length=300, default='', blank=True, help_text="URL prefix if DefectDojo is installed in it's own virtual subdirectory.")
    team_name = models.CharField(max_length=100, default='', blank=True)
    time_zone = models.CharField(max_length=50,
                                 choices=[(tz, tz) for tz in all_timezones],
                                 default='UTC', blank=False)
    display_endpoint_uri = models.BooleanField(default=False, verbose_name="Display Endpoint Full URI", help_text="Displays the full endpoint URI in the endpoint view.")
    enable_product_grade = models.BooleanField(default=False, verbose_name="Enable Product Grading", help_text="Displays a grade letter next to a product to show the overall health.")
    product_grade = models.CharField(max_length=800, blank=True)
    product_grade_a = models.IntegerField(default=90, verbose_name="Grade A", help_text="Percentage score for an 'A' >=")
    product_grade_b = models.IntegerField(default=80, verbose_name="Grade B", help_text="Percentage score for a 'B' >=")
    product_grade_c = models.IntegerField(default=70, verbose_name="Grade C", help_text="Percentage score for a 'C' >=")
    product_grade_d = models.IntegerField(default=60, verbose_name="Grade D", help_text="Percentage score for a 'D' >=")
    product_grade_f = models.IntegerField(default=59, verbose_name="Grade F", help_text="Percentage score for an 'F' <=")
    enable_benchmark = models.BooleanField(default=True, blank=False, verbose_name="Enable Benchmarks",
                            help_text='Enables Benchmarks such as the OWASP ASVS (Application Security Verification Standard)')

class SystemSettingsFormAdmin(forms.ModelForm):
    product_grade = forms.CharField( widget=forms.Textarea )
    class Meta:
        model = System_Settings
        fields = ['product_grade']

class System_SettingsAdmin(admin.ModelAdmin):
    form = SystemSettingsFormAdmin
    fields = ('product_grade',)

def get_current_date():
    return timezone.now().date()


def get_current_datetime():
    return timezone.now()


User = get_user_model()


# proxy class for convenience and UI
class Dojo_User(User):
    class Meta:
        proxy = True

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s (%s)' % (self.first_name,
                                    self.last_name,
                                    self.username)
        return full_name.strip()

    def __unicode__(self):
        return self.get_full_name()


class UserContactInfo(models.Model):
    user = models.OneToOneField(User)
    title = models.CharField(blank=True, null=True, max_length=150)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Phone number must be entered in the format: '+999999999'. "
                                         "Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], blank=True,
                                    max_length=15,
                                    help_text="Phone number must be entered in the format: '+999999999'. "
                                              "Up to 15 digits allowed.")
    cell_number = models.CharField(validators=[phone_regex], blank=True,
                                   max_length=15,
                                   help_text="Phone number must be entered in the format: '+999999999'. "
                                             "Up to 15 digits allowed.")
    twitter_username = models.CharField(blank=True, null=True, max_length=150)
    github_username = models.CharField(blank=True, null=True, max_length=150)
    slack_username = models.CharField(blank=True, null=True, max_length=150, help_text="Email address associated with your slack account", verbose_name="Slack Email Address")
    slack_user_id = models.CharField(blank=True, null=True, max_length=25)
    hipchat_username = models.CharField(blank=True, null=True, max_length=150)
    block_execution = models.BooleanField(default=False, help_text="Instead of async deduping a finding the findings will be deduped synchronously and will 'block' the user until completion.")


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    team = models.CharField(max_length=100)
    is_admin = models.BooleanField(default=False)
    is_globally_read_only = models.BooleanField(default=False)
    updated = models.DateTimeField(editable=False)


class Product_Type(models.Model):
    name = models.CharField(max_length=300)
    critical_product = models.BooleanField(default=False)
    key_product = models.BooleanField(default=False)

    def critical_present(self):

dojo/templates/dojo/ad_hoc_findings.html
{% extends "base.html" %}
{% load event_tags %}
{% load static from staticfiles %}
{% block content %}
    <div>
        <h3> Add findings to a test</h3>
    </div>
    <div>
        <form class="form-horizontal" action="{% url 'ad_hoc_finding' pid %}" method="post">
            {% csrf_token %}
            {% include "dojo/form_fields.html" with form=form %}
            {%  if jform %}
                <h4> JIRA </h4>
                <hr>
                {% include "dojo/form_fields.html" with form=jform %}
            {% endif %}
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <input class="btn btn-primary" type="submit" value="Add Another Finding"/>
                    <input class="btn btn-primary" name="_Finished" type="submit" value="Finished"/>
                </div>
            </div>
        </form>
    </div>
{% endblock %}
{% block postscript %}
    <script type="text/javascript" src="{% static "admin/js/jquery.init.js"%}"></script>
    <script type="application/javascript" src="{% static "admin/js/admin/RelatedObjectLookups.js" %}"></script>
    <script type="application/javascript">
        $ = django.jQuery;
        $('#add_id_endpoints').attr('href', "{% url 'add_endpoint' pid %}?_popup");
        {% if not form_error %}
            $('#id_endpoints').find('option').remove();
        {% endif %}
    </script>


{% endblock %}

dojo/templates/dojo/add_product_meta_data.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% block add_css %}
    <link rel="stylesheet" href="{% static "chosen-bootstrap/chosen.bootstrap.min.css" %}">
{% endblock %}
{% block content %}
    <h3> Add {{ product.name }} Metadata</h3>
    <form class="form-horizontal" method="post">{% csrf_token %}
        {% include "dojo/form_fields.html" with form=form %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-2">
                <input class="btn btn-primary" type="submit" name="add" value="Save"/>
            </div>
            <div class="col-sm-2">
                <input class="btn btn-primary" type="submit" name="add_another" value="Save &amp; Add Another"/>
            </div>
        </div>
    </form>
{% endblock %}

dojo/templates/dojo/calendar.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block add_css %}
    <link rel="stylesheet" href="{% static "chosen-bootstrap/chosen.bootstrap.min.css" %}">
{% endblock %}
{% block content %}
    <form method="GET" id="calfilter" action="/calendar">
        <div class="container-fluid chosen-container side-by-side">
            <div class="row">
                <div class="col-lg-6" style="width:200px;">
                    <select data-placeholder="Calendar type" id="caltype" class="chosen-select">
                        <option value="engagements">Engagements</option>
                        <option value="tests">Tests</option>
                    </select>
                </div>
                <div class="col-lg-6" style="width:400px;">
                    <select data-placeholder="All users" multiple id="lead" name="lead" class="chosen-select">
                        <option value="0">All users</option>
                        <option value="-1">Unassigned</option>
                        {% for u in users %}
                            <option value="{{ u.id }}">{{ u.username }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-lg-6">
                    <button class="btn btn-primary" type="submit">Apply</button>
                </div>
            </div>
        </div>
    </form>
    <br/><br/>
    <div id="calendar"></div>
    <br/><br/>
{% endblock %}
{% block postscript %}
    <script type="application/javascript" src="{% static "chosen/chosen.jquery.min.js" %}"></script>
    <script>
          $(function () {
            $('#caltype').change(function() { $('#calfilter').attr('action', '/calendar/' + $(this).val()); });
            $(".chosen-select").chosen({disable_search_threshold: 10});
            $('#caltype').val('{{ caltype }}'); $('#caltype').trigger('change');
            $('#lead').val([{% for lead in leads %} '{{ lead }}', {% endfor %}]);
            $('.chosen-select').trigger('chosen:updated');
            $('#calendar').fullCalendar({
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'month,basicWeek,basicDay'
                },
                editable: false,
                eventLimit: true, // allow "more" link when too many events
                events: [
                    {% if caltype == 'tests' %}
                        {% for t in tests %}
                            {
                                title: '{{t.engagement.product.name}}: {{ t.engagement.name|default:"Unknown" }} - {{ t.test_type }} ({{ t.lead|default:"Unassigned" }})',
                                start: '{{t.target_start|date:"c"}}',
                                end: '{{t.target_end|date:"c"}}',
                                url: '{% url 'view_test' t.id %}',
                                color: {%  if t.engagement.active %}'#337ab7'{% else %}'#b9b9b9'{% endif %},
                                overlap: true
                            },
                        {%  endfor %}                    
                    {% else %}
                        {% for e in engagements %}
                            {
                                title: '{{e.product.name}}: {{ e.name|default:"Unknown" }} ({{ e.lead|default:"Unassigned" }})',
                                start: '{{e.target_start|date:"c"}}',
                                end: '{{e.target_end|date:"c"}}',
                                url: '{% url 'view_engagement' e.id %}',
                                color: {%  if e.active %}'#337ab7'{% else %}'#b9b9b9'{% endif %},
                                overlap: true
                            },
                        {%  endfor %}
                    {% endif %}
                ]
            });


        });
    </script>
{% endblock %}

dojo/templates/dojo/edit_object.html
d{% extends "base.html" %}
{% load static from staticfiles %}
{% block add_css %}
    <link rel="stylesheet" href="{% static "chosen-bootstrap/chosen.bootstrap.min.css" %}">
{% endblock %}
{% block content %}
    <h3>Edit Tracked Files</h3>
    <form class="form-horizontal" enctype="multipart/form-data" method="post">{% csrf_token %}
        {% include "dojo/form_fields.html" with form=tform %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input class="btn btn-primary" type="submit" value="Submit"/>
            </div>
        </div>
    </form>
{% endblock %}
{% block postscript %}
    <script type="application/javascript" src="{% static "chosen/chosen.jquery.min.js" %}"></script>
    <script type="application/javascript">
        $(function () {
            $('#id_tags').chosen({
                'placeholder_text_multiple': 'Select or add some tags...',
                'no_results_text': "Tag not found, press TAB key to add.",
            });

            $(".search-field").find("input").on("keydown", function (evt) {
                var stroke;
                stroke = (_ref = evt.which) != null ? _ref : evt.keyCode;
                if (stroke == 9) { // 9 = tab key
                    $('#id_tags').append('<option value="' + $(this).val() + '" selected="selected">' + $(this).val() + '</option>');
                    $('#id_tags').trigger('chosen:updated');
                    $('#id_tags').focus();
                    return false;
                }
            });
        });
    </script>
{% endblock %}

dojo/templates/dojo/exist_new_product.html
{% extends "base.html" %}
{% block content %}
    <h3> Register a new Product! </h3>
    <b><span class="text-error"> That product is already registered</span> </b>
    <form class="form-horizontal" action="{% url 'new_product' %}" method="post">{% csrf_token %}
        {% include "dojo/form_fields.html" with form=form %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input class="btn btn-primary" type="submit" value="Submit"/>
            </div>
        </div>
    </form>
{% endblock %}

dojo/templates/dojo/filter_js_snippet.html
{% load static from staticfiles %}
<script type="application/javascript" src="{% static "chosen/chosen.jquery.min.js" %}"></script>
<script type="application/javascript">
    $(function () {
        $(".{{ request.path|slugify }}-filters :input").not("button").addClass("form-control input-sm");
        $(".{{ request.path|slugify }}-filters label").css("display", "block");

        $(".{{ request.path|slugify }}-filters input[type=text]").each(function () {
            var id = this.id;
            var label = $("label[for=" + id + "]");
            $(this).attr("placeholder", label.html().replace(':', "..."));
        });

        var toggle = $(' <button id="show-filters" data-toggle="collapse" data-target="#the-filters" class="btn btn-primary"> <i class="fa fa-filter"></i> <i class="caret"></i> </button>')
        $(".has-filters .dropdown.pull-right").prepend(toggle);
        toggle.on('click', function () {
            $(this).toggleClass("dropup");
        })

        $('.{{ request.path|slugify }}-filters select[multiple=multiple]').each(function () {
            var id = this.id
            var label = $("label[for=" + id + "]");
            $(this).chosen({
                'placeholder_text_multiple': label.html().replace(':', "..."),
                'width': '200px !important'
            });
        })


    })
</script>

dojo/templates/dojo/new_tool_type.html
{% extends "base.html"%}
{% block content %}
 {{ block.super }}
    <h3> Add a Tool Type Configuration </h3>
    <form class="form-horizontal" action="{% url 'add_tool_type' %}" method="post">{% csrf_token %}
     {% include "dojo/form_fields.html" with form=tform %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input class="btn btn-primary" type="submit" value="Submit"/>
            </div>
        </div>
    </form>
{% endblock %}

dojo/templates/dojo/test_type.html
{% extends "base.html" %}
{% load navigation_tags %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading tight">
                    <h3 class="has-filters">
                        Test Type List
                        <div class="dropdown pull-right">
                            <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenu1"
                                    data-toggle="dropdown" aria-expanded="true">
                                <span class="fa fa-wrench"></span>
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu dropdown-menu-right" role="menu"
                                aria-labelledby="dropdownMenu1">
                                {% if request.user.is_staff %}
                                    <li role="presentation">
                                        <a href="{%  url 'add_test_type' %}">
                                            <i class="fa fa-plus"></i> New Test Type </a>
                                    </li>
                                {% endif %}
                            </ul>
                        </div>
                    </h3>
                </div>
                <div id="the-filters" class="panel-body collapse {% if request.META.QUERY_STRING %}in{% endif %}">
                    {% include "dojo/filter_snippet.html" with form=test_types.form %}
                </div>
            </div>
            {% if tts %}
                <div class="clearfix">
                    {% include "dojo/paging_snippet.html" with page=tts page_size=True %}
                </div>
                <div class="panel panel-default table-responsive">
                    <table id="test_types"
                           class="tablesorter-bootstrap table table-bordered table-condensed table-striped">
                        <thead>
                        <tr>
                            <th>{% dojo_sort request 'Test Type' 'name' 'asc' %}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for tt in tts %}
                            <tr>
                                {% if user.is_staff %}
                                    <td><a href="{% url 'edit_test_type' tt.id %}"> {{ tt.name }} </a></td>
                                {% else %}
                                    <td> {{ tt.name }} </a> </td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="clearfix">
                    {% include "dojo/paging_snippet.html" with page=tts page_size=True %}
                </div>
            {% else %}
                <p class="text-center">No test types found.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}
{% block postscript %}
    <script>
        $(function () {
            var availableTags = [
                {% for word in name_words %}
                    "{{word}}",
                {% endfor %}
            ];
            $("#id_name").autocomplete({
                source: availableTags
            });
        });
    </script>
    {% include "dojo/filter_js_snippet.html" %}
{% endblock %}